### ISSUE TITLE
Changing prng seed?

### ISSUE THREAD

**Issue by jamesETsmith** [jasonriedy/GrB-mxm-timer#2]
# Overview

@jasonriedy, do you remember how to seed the seed dynamically for this? Initially I thought I could using the code fragment below, but it turns out to be unused (I think).

https://github.com/jasonriedy/GrB-mxm-timer/blob/bef3122b19b9f32eeca87ff7d78b5f6ace6408e9/prng.c#L28-L49

**Comment by jasonriedy** [comment]
That... would be a bug. It's been a long, long time since I poked at this code. Being more dynamic was against the point...

**Comment by jamesETsmith** [comment]
Just for closure, in line with what Jason said, there is no way to do this dynamically. Closing this issue.
